-- Module contains native vim / nvim global settings
require("native/opts/display")
require("native/opts/completeopt")
require("native/opts/diagnostic")
require("native/opts/colorscheme")
require("native/opts/format")
require("native/opts/terminal")
require("native/opts/netrw")
require("native/opts/input")
require("native/opts/select")
require("native/opts/diff")
require("native/opts/autoreload")
